dataset:
  path: mevs/data/MEVS.json
  question_set: [0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 25, 26, 27, 28, 29, 30, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 86, 87, 88, 89, 118, 119, 120, 121, 122, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138]
  languages: ["FRE_FR", "SPA_ES", "POR_PT", "GER_DE", "CZE_CZ", "RUS_RU", "NOR_NO", "ENG_GB"]

prompt:
  symbols: ["letters", "numbers"]
  tail: ["none", "space", "newline"]
  order: ["all"] #["default", "random"]

models:
  - QuixiAI/Wizard-Vicuna-7B-Uncensored
  - Qwen/Qwen2.5-7B-Instruct

precision: 32
output_dir: results/
